eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registerWithEureka: true

ribbon:
  eureka:
    enabled: true

zuul:
  prefix: /api
  routes:
    micro-service-1:
      path: /service1/**
      serviceId: MICRO-SERVICE-1
    micro-service-2:
      path: /service2/**
      serviceId: MICRO-SERVICE-2
spring:
  zipkin:
    base-url: http://localhost:9411/
    sender:
      type: web
  sleuth:
    sampler:
      percentage: 1.0
server:
  port: 8080