msg : micro service 2 load balancer - Hello world - this is from config server for DEV branch Master
branch: Master
server:
  port: 8082
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registerWithEureka: true
    fetchRegistry: true
  instance:
    preferIpAddress: true
management:
  security:
    enabled: false
spring:
  zipkin:
    base-url: http://localhost:9411/
    sender:
      type: web
  sleuth:
    sampler:
      percentage: 1.0